### ISSUE TITLE
no vcf output

### ISSUE THREAD

**Issue by adriludwig** [kensung-lab/INSurVeyor#11]
Hi! I'm using Insurveyor to identify TEs in several samples. For most of them, I got the vcf results, however, for a few, I'm not getting the correct output. This is the error message, but I couldn't figure out what is the problem. Any clues? Thanks very much

...
Segmentation fault
DC remapped in 1 [s]
Executing: /pub63/adriana/conda/envs/ins/bin/add_filtering_info /data/adriana/BBSRC_wildflies/BBSRC_mutagenesis_lines/Ins/Sample_44-J07_TJ_MAE_11_fixed.bam /data/adriana/BBSRC_wildflies/BBSRC_mutagenesis_lines/Ins/Ins_Sample_44-J07_TJ_MAE_11 /data/adriana/BBSRC_wildflies/reference/dmel-all-chromosome-r6.47.fasta
[E::hts_open_format] Failed to open file "/data/adriana/BBSRC_wildflies/BBSRC_mutagenesis_lines/Ins/Ins_Sample_44-J07_TJ_MAE_11/assembled_ins.vcf.gz" : No such file or directory
Segmentation fault
Filtering info added in 0 [s]
Executing: /pub63/adriana/conda/envs/ins/bin/filter /data/adriana/BBSRC_wildflies/BBSRC_mutagenesis_lines/Ins/Ins_Sample_44-J07_TJ_MAE_11 /data/adriana/BBSRC_wildflies/reference/dmel-all-chromosome-r6.47.fasta 0.25
[E::hts_open_format] Failed to open file "/data/adriana/BBSRC_wildflies/BBSRC_mutagenesis_lines/Ins/Ins_Sample_44-J07_TJ_MAE_11/transurveyor_ins.annotated.vcf.gz" : No such file or directory
terminate called after throwing an instance of 'std::runtime_error'
  what():  Unable to open file /data/adriana/BBSRC_wildflies/BBSRC_mutagenesis_lines/Ins/Ins_Sample_44-J07_TJ_MAE_11/transurveyor_ins.annotated.vcf.gz.
Aborted

**Comment by Mesh89** [comment]
Hi,

Do you have the complete log? Those error messages are due to the process not finding the files it expects, meaning a previous process failed to terminate correctly.

Is any of the data available for me to test?

**Comment by adriludwig** [comment]
Hi, Thanks for your quick message. It would be wonderful if you could test. I've been trying to fix this for a long time.

Here are what I think you need. https://drive.google.com/drive/folders/1GyDEHP_-V02zSqDzreYEEk9RvevEs9IP?usp=sharing

PS.:the bam file will be uploaded soon

Thanks again for that!

**Comment by Mesh89** [comment]
Thank you. I confirm that I can reproduce the problem. I will investigate it.

**Comment by adriludwig** [comment]
I really appreciate that! Thanks very much

**Comment by Mesh89** [comment]
I have released 1.1.2, which should fix the issue you encountered. I could run it successfully on your sample.
For your reference, I am attaching the output I obtained.
[out.pass.vcf.gz](https://github.com/kensung-lab/INSurVeyor/files/11925395/out.pass.vcf.gz)

**Comment by adriludwig** [comment]
Thanks very much for doing that!

**Comment by Mesh89** [comment]
Thanks for pointing out this bug. Let me know if it fixed your problem and I will close the issue.

**Comment by adriludwig** [comment]
Yes, it fixed the problem. I just finished running the remaining samples. Thanks a lot!
