### ISSUE TITLE
Is it worth saving the INS sequence containing the `INCOMPLETE_ASSEMBLY` tag?

### ISSUE THREAD

**Issue by HuTaoJiaZiAckerman** [kensung-lab/INSurVeyor#13]
Dear developer:
First, we got the `out.pass.vcf.gz` file and found that some SVs contained the `INCOMPLETE_ASSEMBLY` tag. They are missing `SVINSLEN && SVLEN` information for SV. 

Secondly,  these sequences may have been too long to complete the assembly, according to notes in the file. However, we find that the result not support the reason, for exsample, 5549360 - 5549360 = -0 or 9704678 - 9704664 = 14.

Therefore, we want to know whether this SV is valuable to retain and conduct further analysis.
Thirdly, please point out some issues that I have overlooked.

Here are some examples (random selected) :
```
##INFO=<ID=INCOMPLETE_ASSEMBLY,Number=0,Type=Flag,Description="Inserted sequence is too long and only part of it could be assembled.">
NC_010443.5	5549360	A_INS_4	t	<INS>	.	PASS	END=5549360;SVTYPE=INS;INCOMPLETE_ASSEMBLY;SVINSSEQ=TGGAGTTCCCATCATGGCGCAGTGGTTAAGGAATCCGACTAGGAACCATGAGGTTGCAGGTTCGATCCCTGACCTTGCTCAGTGGGTTAAGGATCCGGCATTGCTCTGAGCTGTGGTATGGGTCGCAGCCGCATCTCGGATCCCAAGGTTGCGGTGGCTACAGCTCTGATTGAACCC-AAAAAACAAACAAAAAAAAGAAAGTTATGGATCTT;SPLIT_READS=4,3;FWD_SPLIT_READS=1,0;REV_SPLIT_READS=3,3;DISCORDANT=5,4;ALGORITHM=assembly;LEFT_ANCHOR=5549279-5549360;RIGHT_ANCHOR=5549360-5549538;AVG_STABLE_NM=0,1;STABLE_DEPTHS=7,3;SPANNING_READS=0,0	GT	1
NC_010443.5	9704664	A_INS_5	t	<INS>	.	PASS	END=9704678;SVTYPE=INS;INCOMPLETE_ASSEMBLY;SVINSSEQ=CTCTCTTTCTCTCTTTCTTTCTCTCTTTCTCTCTCTCTCTCTCTGTCTCTCTCTCGCGCTCTCTTTCTTTCT-ATTTGTAGTAGTTCTGTGAAAAATGCCATTGGTATTTTGATAGGGATTGCATTGAGTCTGTAGATTGCTTTGGATAGTATGGTCATTTTAACAGTATTAACTCTTCCAATCCATGAACACAGTATATCTTTGCATCTGTTTGTACTGTCTTCAATTTCTTTCATCAATGTCTTAATTTTCTGAATATAGGTCTTTTATTTCCTTAGGTAAGTTTATTCATAGGTATTTATTCTGTCTGATGCAATGGTAAGTGGGATTATTTCCTCAATTTCTCTTTTTGATTGTTAATTGTTACTGTTATAGGGATGCAACAGATTTCTGTATAATAAA;SPLIT_READS=3,3;FWD_SPLIT_READS=2,2;REV_SPLIT_READS=1,1;DISCORDANT=2,23;ALGORITHM=assembly;LEFT_ANCHOR=9704580-9704663;RIGHT_ANCHOR=9704678-9704932;AVG_STABLE_NM=0,0;STABLE_DEPTHS=5,12;SPANNING_READS=0,0	GT	1
NC_010457.5	26440462	A_INS_407	T	<INS>	.	PASS	END=26440462;SVTYPE=INS;SVINSLEN=154;SVLEN=154;SVINSSEQ=TTGCTGATCCTAGAAACCTTTGTTGGTGTTCTTTGCTTGAATAATTCACAAAATGATAAGAAGGTACAATATACCACTGAATATTAACCATAGTCATGTATTCTCCTTCTAACAAAAGTTTTAATAGTCTCCATTCAACTAAAAAAAGACAGGT;SPLIT_READS=4,3;FWD_SPLIT_READS=2,1;REV_SPLIT_READS=2,2;DISCORDANT=8,6;ALGORITHM=assembly;LEFT_ANCHOR=26440384-26440461;RIGHT_ANCHOR=26440462-26440546;AVG_STABLE_NM=0,0;STABLE_DEPTHS=6,3;SPANNING_READS=1,1	GT	1
NC_010457.5	29389673	T_INS_342	a	<INS>	.	PASS	END=29389722;SVTYPE=INS;SVINSLEN=132;SVLEN=83;SVINSSEQ=ATAGCATTGAGAACTCTGTCTAGATACTCATGCTGCAACAGAAGAAAGGCTGGGGGAAAAATGTAATTGTAATGTACACATGTAAGGATAACCTGACCCCCTTGCTGTACAGTGGGAAAATAAAAAAAAAAA;SPLIT_READS=8,0;FWD_SPLIT_READS=4,0;REV_SPLIT_READS=4,0;DISCORDANT=3,2;ALGORITHM=transurveyor;IMPRECISE;LEFT_ANCHOR=29389402-29389672;RIGHT_ANCHOR=29389722-29390000;LEFT_ANCHOR_CIGAR=178=3I14=1I6=1X5=1X33=1X25=68S;RIGHT_ANCHOR_CIGAR=64S110=1X21=1I91=1X26=1X9=1X11=;AVG_STABLE_NM=0,0;TRANS_QUERY_COV=132,132;STABLE_DEPTHS=7,8;SPANNING_READS=1,1;MHLEN=0;SCORES=0.916667,0.666667	GT	1
```

**Comment by Mesh89** [comment]
Hi,

1) Yes, INCOMPLETE_ASSEMBLY will not have SVINSLEN and SVLEN, because the length of the insertion is not known.
2) I did not understand the second point. INCOMPLETE_ASSEMBLY means that the *inserted sequence* was too long/had too few reads to be fully assembled. POS and END refer to the location of the insertion site, they have nothing to do with the length of the inserted sequence.
3) It depends on the analysis you are planning to conduct. If the analysis requires the full sequence, then they may not be useful. Otherwise, you may retain them.

**Comment by HuTaoJiaZiAckerman** [comment]
Hi,
Thank you very much for your answer, I have already made up my mind whether to keep this sequence or not.

About the second point, it is based on the comment information in the vcf file.
I found such a sequence in the vcf file.
```
##INFO=<ID=INCOMPLETE_ASSEMBLY,Number=0,Type=Flag,Description="Inserted sequence is too long and only part of it could be assembled.">
```
So, I suddenly became interested in POS and END with INCOMPLETE_ASSEMBLY tag sequence.
```
NC_010443.5	5549360	A_INS_4	t	<INS>	.	PASS	END=5549360;SVTYPE=INS;INCOMPLETE_ASSEMBLY;SVINSSEQ=TGGAGTTCCCATCATGGCGCAGTGGTTAAGGAATCCGACTAGGAACCATGAGGTTGCAGGTTCGATCCCTGACCTTGCTCAGTGGGTTAAGGATCCGGCATTGCTCTGAGCTGTGGTATGGGTCGCAGCCGCATCTCGGATCCCAAGGTTGCGGTGGCTACAGCTCTGATTGAACCC-AAAAAACAAACAAAAAAAAGAAAGTTATGGATCTT;SPLIT_READS=4,3;FWD_SPLIT_READS=1,0;REV_SPLIT_READS=3,3;DISCORDANT=5,4;ALGORITHM=assembly;LEFT_ANCHOR=5549279-5549360;RIGHT_ANCHOR=5549360-5549538;AVG_STABLE_NM=0,1;STABLE_DEPTHS=7,3;SPANNING_READS=0,0	GT	1
NC_010443.5	9704664	A_INS_5	t	<INS>	.	PASS	END=9704678;SVTYPE=INS;INCOMPLETE_ASSEMBLY;SVINSSEQ=CTCTCTTTCTCTCTTTCTTTCTCTCTTTCTCTCTCTCTCTCTCTGTCTCTCTCTCGCGCTCTCTTTCTTTCT-ATTTGTAGTAGTTCTGTGAAAAATGCCATTGGTATTTTGATAGGGATTGCATTGAGTCTGTAGATTGCTTTGGATAGTATGGTCATTTTAACAGTATTAACTCTTCCAATCCATGAACACAGTATATCTTTGCATCTGTTTGTACTGTCTTCAATTTCTTTCATCAATGTCTTAATTTTCTGAATATAGGTCTTTTATTTCCTTAGGTAAGTTTATTCATAGGTATTTATTCTGTCTGATGCAATGGTAAGTGGGATTATTTCCTCAATTTCTCTTTTTGATTGTTAATTGTTACTGTTATAGGGATGCAACAGATTTCTGTATAATAAA;SPLIT_READS=3,3;FWD_SPLIT_READS=2,2;REV_SPLIT_READS=1,1;DISCORDANT=2,23;ALGORITHM=assembly;LEFT_ANCHOR=9704580-9704663;RIGHT_ANCHOR=9704678-9704932;AVG_STABLE_NM=0,0;STABLE_DEPTHS=5,12;SPANNING_READS=0,0	GT	1
```
According to POS and END information, I see SVLEN=0 in the first sequence, and SVLEN=14 in the second sequence, which does not seem to be the real SV.

But, one interesting thing is that SVINSSEQ gives the information of the inserted sequence in the INFO column.

So, this leaves me a bit ambiguous, please also explain some reason.

Best wishes for you!

**Comment by Mesh89** [comment]
SVLEN is *NOT* END-POS.
SVLEN is defined as the difference in length between the alternative and the reference allele. Intuitively, you can think of it as "how much the length of the genome changes due to this SV" (negative if the size decreases, e.g. due to a deletion). In this case, because we don't know how long the inserted sequence is, we don't know how much the size of the genome increases, therefore we don't know the SVLEN.

In case of A_INS_4, we know that the SVLEN is at least 212 (because the partial inserted sequence reported is 212), but it may be much more.

**Comment by HuTaoJiaZiAckerman** [comment]
Thank you very much for your answer to this question, I have no more questions. 


Thank you very much.
