### ISSUE TITLE
ValueError: cannot convert float NaN to integer

### ISSUE THREAD

**Issue by Mudke** [kensung-lab/INSurVeyor#14]
Hello!

I am having trouble with this error

Average depth: 0.059455738629551
Traceback (most recent call last):
  File "insurveyor.py", line 123, in <module>
    mean_is = int(np.mean(general_dist))
ValueError: cannot convert float NaN to integer

I tried to modify the line with mean_is=int(np.nanmean(general_dist)) but still it is not working.

**Comment by Mesh89** [comment]
I find puzzling the extremely low average depth. It looks like you almost have no reads.
The NaN is probably because the random sampling fails to collect any reads. Can you print general_dist?

**Comment by Mudke** [comment]
I did print the general_dist but it printed the same error. I will try to check the bam files if it has any reads mapped or not. What should be the range of average depth?

**Comment by Mesh89** [comment]
It depends. If you are doing WGS, I would say you start getting good results at 15x, 30x or more is ideal.
You should print general_dist before the line that causes the error, which seems to be: mean_is = int(np.mean(general_dist))

**Comment by hanliu0119** [comment]
I have the same error, and here is the error message:

/home/.conda/envs/insurveyor-env/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/.conda/envs/insurveyor-env/lib/python3.10/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/.conda/envs/insurveyor-env/lib/python3.10/site-packages/numpy/core/_methods.py:206: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/.conda/envs/insurveyor-env/lib/python3.10/site-packages/numpy/core/_methods.py:163: RuntimeWarning: invalid value encountered in divide
  arrmean = um.true_divide(arrmean, div, out=arrmean,
/home/.conda/envs/insurveyor-env/lib/python3.10/site-packages/numpy/core/_methods.py:198: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
Average depth: 5.659557216914101
Traceback (most recent call last):
  File "/INSurVeyor/insurveyor.py", line 125, in <module>
   ` mean_is = int(np.mean(general_dist))`
ValueError: cannot convert float NaN to integer

**Comment by Mesh89** [comment]
Can you print the variable general_dist before the line that fails? I.e. before mean_is = int(np.mean(general_dist))

**Comment by dmjask** [comment]
Hi, I'm currently having this issue, although I do not have WGS data, only a smaller region. When using a whole chromosome reference, the software runs without error but the output file is empty. However, providing a reference reduced to match the region of reads results in the error above - with average depth of 0.0, where 10-20 is expected. 
Any suggestions?

**Comment by Mesh89** [comment]
Hi, 

How did you reduce the reference? Did you remove contigs without reads? 
If you removed parts of chromosomes, did you also remap the reads to ensure the coordinates are consistent with the new reduced reference?

**Comment by dmjask** [comment]
Reduced the reference through samtools view to specific span. All of reference is a singular contig.
The reads were extracted with samtools for the same span and remapped to the reduced reference for consistent coordinates. All mapping done by minimap2. 
Renaming the contig in reference to exclude the coordinates of the span fixed the depth issue, but the ValueError persists.

**Comment by Mesh89** [comment]
The randomly generated positions insurveyor uses are in the workdir, in a file named random_pos.txt

Do those coordinates make sense? Can you select a few of them and have a look at the BAM file at those positions through IGV (using the same reference and BAM you are using to run insurveyor)? Do they have reads?

Note that insurveyor also has a --sampling-regions option where you can pass a BED file. It will only sample positions within those intervals. That should be easier than subsetting the reference.

**Comment by dmjask** [comment]
The coordinates make sense, all are within the limits of the size of the new subset reference. BAMs in IGV also make sense, and I assume the correct calculated depth confirms this. 

I will try the BED approach next
