### ISSUE TITLE
Update to htslib 1.18?

### ISSUE THREAD

**Issue by zihhuafang** [kensung-lab/INSurVeyor#15]
Hi @Mesh89 ,
Thanks a lot for developing the collection of tools to call SV with WGS data.
I am looking to call insertion with INSurVeyor and deletions/duplications with SurVIndel2 using CRAM.

I noticed that there's an update of htslib version (1.18) for SurVIndel2. 
Wonder if htslib version of INSurVeyor will be updated as well and will that have impact on insertion calling using CRAM? 

Thanks a lot!

**Comment by Mesh89** [comment]
Hi,
I do not have plans to update INSurVeyor right now. The newer version of htslib should not have an impact on the results.
If in the future I will find myself updating the software for bug fixing or other reasons, I may also update the libraries to the latest version.

**Comment by zihhuafang** [comment]
Hi, 
Thanks! Good to know that htslib version does not have impact on INSurVeyor results.
Will use the most recent release.
