### ISSUE TITLE
large genome index

### ISSUE THREAD

**Issue by toto2011** [kensung-lab/INSurVeyor#17]
We would like to try INSurVeyor to identify TIPs along wheat chromosomes but their size exceeds the limit of 512Mb to generate a bai index. To overcome this, we usually use the -c flag to generate a csi index. While the program is running, it seems to generate an intermediate bam file and tries to index it with default settings but fails due to the size of the chromosomes. Is there a way to bypass this? or change somehow the settings to generate a csi instead of bai?

**Comment by Mesh89** [comment]
Hi,

I was not aware of this issue. Let me check if I can switch to csi indices for the intermediate bam files.

**Comment by Mesh89** [comment]
I have added a --use-csi option. Would you be able to clone the latest commit and check if it works for you?
