### ISSUE TITLE
Source of the inserted sequence

### ISSUE THREAD

**Issue by Meetmet21** [kensung-lab/INSurVeyor#19]
Hello,

I would like to know if it's possible to infer the source of the inserted sequence from th resulting VCF file? For example, if the inserted sequence comes from the chromsome two into the chromosome one, is there a way to have this information?

Otherwise, very interesting soft, thank you!

**Comment by Mesh89** [comment]
Hello,

I don't think it is possible to be certain about the source of the insertion. Illumina reads will not contain that information.

However, you could BLAST (or any other mapping software) the inserted sequence to the reference genome. If there is a very good hit that is unique, it may be reasonable to infer that that is the source of a transposition.
If there is no hit, sometimes insertions may be due foreign DNA being inserted, e.g., viruses such as HBV and HPV. I believe using the BLAST hosted at NCBI it is possible to query large collections of DNA from various sources.
Also, some "insertions" may not actually be insertions, but deletions in the reference genome.

Thank you!
