### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by mrburke00** [kensung-lab/INSurVeyor#2]
Hi, Im getting a slew of errors when trying to run the make command.  Not entirely sure where to start debugging. Any advice would be much appreciated. 

`[ 61%] Building CXX object CMakeFiles/dc_remapper.dir/dc_remapper.cpp.o
In file included from /usr/include/c++/4.8.2/algorithm:62:0,
                 from /scratch/Shares/layer/workspace/devin_sra/repeat_masker/local/src/INSurVeyor/dc_remapper.cpp:6:
/usr/include/c++/4.8.2/bits/stl_algo.h: In instantiation of ‘_RandomAccessIterator std::__unguarded_partition(_RandomAccessIterator, _RandomAccessIterator, const _Tp&, _Compare) [with _RandomAccessIterator = __gnu_cxx::__normal_iterator<std::pair<std::basic_string<char>, StripedSmithWaterman::Alignment>*, std::vector<std::pair<std::basic_string<char>, StripedSmithWaterman::Alignment> > >; _Tp = std::pair<std::basic_string<char>, StripedSmithWaterman::Alignment>; _Compare = generate_reference_guided_consensus(std::string, reads_cluster_t*, reads_cluster_t*, std::unordered_map<std::basic_string<char>, std::basic_string<char> >&, StripedSmithWaterman::Aligner&, StripedSmithWaterman::Aligner&, std::vector<StripedSmithWaterman::Alignment>&, std::string&)::__lambda2]’:
/usr/include/c++/4.8.2/bits/stl_algo.h:2296:78:   required from ‘_RandomAccessIterator std::__unguarded_partition_pivot(_RandomAccessIterator, _RandomAccessIterator, _Compare) [with _RandomAccessIterator = __gnu_cxx::__normal_iterator<std::pair<std::basic_string<char>, StripedSmithWaterman::Alignment>*, std::vector<std::pair<std::basic_string<char>, StripedSmithWaterman::Alignment> > >; _Compare = generate_reference_guided_consensus(std::string, reads_cluster_t*, reads_cluster_t*, std::unordered_map<std::basic_string<char>, std::basic_string<char> >&, StripedSmithWaterman::Aligner&, StripedSmithWaterman::Aligner&, std::vector<StripedSmithWaterman::Alignment>&, std::string&)::__lambda2]’
/usr/include/c++/4.8.2/bits/stl_algo.h:2337:62:   required from ‘void std::__introsort_loop(_RandomAccessIterator, _RandomAccessIterator, _Size, _Compare) [with _RandomAccessIterator = __gnu_cxx::__normal_iterator<std::pair<std::basic_string<char>, StripedSmithWaterman::Alignment>*, std::vector<std::pair<std::basic_string<char>, StripedSmithWaterman::Alignment> > >; _Size = long int; _Compare = generate_reference_guided_consensus(std::string, reads_cluster_t*, reads_cluster_t*, std::unordered_map<std::basic_string<char>, std::basic_string<char> >&, StripedSmithWaterman::Aligner&, StripedSmithWaterman::Aligner&, std::vector<StripedSmithWaterman::Alignment>&, std::string&)::__lambda2]’
/usr/include/c++/4.8.2/bits/stl_algo.h:5499:44:   required from ‘void std::sort(_RAIter, _RAIter, _Compare) [with _RAIter = __gnu_cxx::__normal_iterator<std::pair<std::basic_string<char>, StripedSmithWaterman::Alignment>*, std::vector<std::pair<std::basic_string<char>, StripedSmithWaterman::Alignment> > >; _Compare = generate_reference_guided_consensus(std::string, reads_cluster_t*, reads_cluster_t*, std::unordered_map<std::basic_string<char>, std::basic_string<char> >&, StripedSmithWaterman::Aligner&, StripedSmithWaterman::Aligner&, std::vector<StripedSmithWaterman::Alignment>&, std::string&)::__lambda2]’
/scratch/Shares/layer/workspace/devin_sra/repeat_masker/local/src/INSurVeyor/assemble.h:306:3:   required from here
/usr/include/c++/4.8.2/bits/stl_algo.h:2263:35: error: no match for call to ‘(generate_reference_guided_consensus(std::string, reads_cluster_t*, reads_cluster_t*, std::unordered_map<std::basic_string<char>, std::basic_string<char> >&, StripedSmithWaterman::Aligner&, StripedSmithWaterman::Aligner&, std::vector<StripedSmithWaterman::Alignment>&, std::string&)::__lambda2) (std::pair<std::basic_string<char>, StripedSmithWaterman::Alignment>&, const std::pair<std::basic_string<char>, StripedSmithWaterman::Alignment>&)’
    while (__comp(*__first, __pivot))
                                   ^
In file included from /scratch/Shares/layer/workspace/devin_sra/repeat_masker/local/src/INSurVeyor/dc_remapper.cpp:19:0:
/scratch/Shares/layer/workspace/devin_sra/repeat_masker/local/src/INSurVeyor/assemble.h:304:5: note: candidates are:
    [](std::pair<std::string, StripedSmithWaterman::Alignment>& p1, std::pair<std::string, StripedSmithWaterman::Alignment>& p2) {
     ^
In file included from /usr/include/c++/4.8.2/algorithm:62:0,
                 from /scratch/Shares/layer/workspace/devin_sra/repeat_masker/local/src/INSurVeyor/dc_remapper.cpp:6:
/usr/include/c++/4.8.2/bits/stl_algo.h:2263:35: note: bool (*)(std::pair<std::basic_string<char>, StripedSmithWaterman::Alignment>&, std::pair<std::basic_string<char>, StripedSmithWaterman::Alignment>&) <conversion>
    while (__comp(*__first, __pivot))
                                   ^
/usr/include/c++/4.8.2/bits/stl_algo.h:2263:35: note:   candidate expects 3 arguments, 3 provided
In file included from /scratch/Shares/layer/workspace/devin_sra/repeat_masker/local/src/INSurVeyor/dc_remapper.cpp:19:0:
/scratch/Shares/layer/workspace/devin_sra/repeat_masker/local/src/INSurVeyor/assemble.h:304:127: note: generate_reference_guided_consensus(std::string, reads_cluster_t*, reads_cluster_t*, std::unordered_map<std::basic_string<char>, std::basic_string<char> >&, StripedSmithWaterman::Aligner&, StripedSmithWaterman::Aligner&, std::vector<StripedSmithWaterman::Alignment>&, std::string&)::__lambda2
    [](std::pair<std::string, StripedSmithWaterman::Alignment>& p1, std::pair<std::string, StripedSmithWaterman::Alignment>& p2) {
                                                                                                                               ^
/scratch/Shares/layer/workspace/devin_sra/repeat_masker/local/src/INSurVeyor/assemble.h:304:127: note:   no known conversion for argument 2 from ‘const std::pair<std::basic_string<char>, StripedSmithWaterman::Alignment>’ to ‘std::pair<std::basic_string<char>, StripedSmithWaterman::Alignment>&’
In file included from /usr/include/c++/4.8.2/algorithm:62:0,
                 from /scratch/Shares/layer/workspace/devin_sra/repeat_masker/local/src/INSurVeyor/dc_remapper.cpp:6:
/usr/include/c++/4.8.2/bits/stl_algo.h:2266:34: error: no match for call to ‘(generate_reference_guided_consensus(std::string, reads_cluster_t*, reads_cluster_t*, std::unordered_map<std::basic_string<char>, std::basic_string<char> >&, StripedSmithWaterman::Aligner&, StripedSmithWaterman::Aligner&, std::vector<StripedSmithWaterman::Alignment>&, std::string&)::__lambda2) (const std::pair<std::basic_string<char>, StripedSmithWaterman::Alignment>&, std::pair<std::basic_string<char>, StripedSmithWaterman::Alignment>&)’
    while (__comp(__pivot, *__last))
                                  ^
In file included from /scratch/Shares/layer/workspace/devin_sra/repeat_masker/local/src/INSurVeyor/dc_remapper.cpp:19:0:
/scratch/Shares/layer/workspace/devin_sra/repeat_masker/local/src/INSurVeyor/assemble.h:304:5: note: candidates are:
    [](std::pair<std::string, StripedSmithWaterman::Alignment>& p1, std::pair<std::string, StripedSmithWaterman::Alignment>& p2) {
     ^
In file included from /usr/include/c++/4.8.2/algorithm:62:0,
                 from /scratch/Shares/layer/workspace/devin_sra/repeat_masker/local/src/INSurVeyor/dc_remapper.cpp:6:
/usr/include/c++/4.8.2/bits/stl_algo.h:2266:34: note: bool (*)(std::pair<std::basic_string<char>, StripedSmithWaterman::Alignment>&, std::pair<std::basic_string<char>, StripedSmithWaterman::Alignment>&) <conversion>
    while (__comp(__pivot, *__last))
                                  ^
/usr/include/c++/4.8.2/bits/stl_algo.h:2266:34: note:   candidate expects 3 arguments, 3 provided
In file included from /scratch/Shares/layer/workspace/devin_sra/repeat_masker/local/src/INSurVeyor/dc_remapper.cpp:19:0:
/scratch/Shares/layer/workspace/devin_sra/repeat_masker/local/src/INSurVeyor/assemble.h:304:127: note: generate_reference_guided_consensus(std::string, reads_cluster_t*, reads_cluster_t*, std::unordered_map<std::basic_string<char>, std::basic_string<char> >&, StripedSmithWaterman::Aligner&, StripedSmithWaterman::Aligner&, std::vector<StripedSmithWaterman::Alignment>&, std::string&)::__lambda2
    [](std::pair<std::string, StripedSmithWaterman::Alignment>& p1, std::pair<std::string, StripedSmithWaterman::Alignment>& p2) {
                                                                                                                               ^
/scratch/Shares/layer/workspace/devin_sra/repeat_masker/local/src/INSurVeyor/assemble.h:304:127: note:   no known conversion for argument 1 from ‘const std::pair<std::basic_string<char>, StripedSmithWaterman::Alignment>’ to ‘std::pair<std::basic_string<char>, StripedSmithWaterman::Alignment>&’
In file included from /usr/include/c++/4.8.2/algorithm:62:0,
                 from /scratch/Shares/layer/workspace/devin_sra/repeat_masker/local/src/INSurVeyor/dc_remapper.cpp:6:
/usr/include/c++/4.8.2/bits/stl_algo.h: In instantiation of ‘_RandomAccessIterator std::__unguarded_partition(_RandomAccessIterator, _RandomAccessIterator, const _Tp&, _Compare) [with _RandomAccessIterator = __gnu_cxx::__normal_iterator<remap_info_t*, std::vector<remap_info_t> >; _Tp = remap_info_t; _Compare = get_strict_region_start(std::vector<remap_info_t>&, std::vector<remap_info_t>&)::__lambda14]’:
/usr/include/c++/4.8.2/bits/stl_algo.h:2296:78:   required from ‘_RandomAccessIterator std::__unguarded_partition_pivot(_RandomAccessIterator, _RandomAccessIterator, _Compare) [with _RandomAccessIterator = __gnu_cxx::__normal_iterator<remap_info_t*, std::vector<remap_info_t> >; _Compare = get_strict_region_start(std::vector<remap_info_t>&, std::vector<remap_info_t>&)::__lambda14]’
/usr/include/c++/4.8.2/bits/stl_algo.h:2337:62:   required from ‘void std::__introsort_loop(_RandomAccessIterator, _RandomAccessIterator, _Size, _Compare) [with _RandomAccessIterator = __gnu_cxx::__normal_iterator<remap_info_t*, std::vector<remap_info_t> >; _Size = long int; _Compare = get_strict_region_start(std::vector<remap_info_t>&, std::vector<remap_info_t>&)::__lambda14]’
/usr/include/c++/4.8.2/bits/stl_algo.h:5499:44:   required from ‘void std::sort(_RAIter, _RAIter, _Compare) [with _RAIter = __gnu_cxx::__normal_iterator<remap_info_t*, std::vector<remap_info_t> >; _Compare = get_strict_region_start(std::vector<remap_info_t>&, std::vector<remap_info_t>&)::__lambda14]’
/scratch/Shares/layer/workspace/devin_sra/repeat_masker/local/src/INSurVeyor/dc_remapper.cpp:185:89:   required from here
/usr/include/c++/4.8.2/bits/stl_algo.h:2263:35: error: no match for call to ‘(get_strict_region_start(std::vector<remap_info_t>&, std::vector<remap_info_t>&)::__lambda14) (remap_info_t&, const remap_info_t&)’
    while (__comp(*__first, __pivot))
                                   ^
/scratch/Shares/layer/workspace/devin_sra/repeat_masker/local/src/INSurVeyor/dc_remapper.cpp:185:16: note: candidates are:
               [](remap_info_t& ri1, remap_info_t& ri2) { return ri1.start < ri2.start; });
                ^
In file included from /usr/include/c++/4.8.2/algorithm:62:0,
                 from /scratch/Shares/layer/workspace/devin_sra/repeat_masker/local/src/INSurVeyor/dc_remapper.cpp:6:
/usr/include/c++/4.8.2/bits/stl_algo.h:2263:35: note: bool (*)(remap_info_t&, remap_info_t&) <conversion>
    while (__comp(*__first, __pivot))
                                   ^
/usr/include/c++/4.8.2/bits/stl_algo.h:2263:35: note:   candidate expects 3 arguments, 3 provided
/scratch/Shares/layer/workspace/devin_sra/repeat_masker/local/src/INSurVeyor/dc_remapper.cpp:185:54: note: get_strict_region_start(std::vector<remap_info_t>&, std::vector<remap_info_t>&)::__lambda14
               [](remap_info_t& ri1, remap_info_t& ri2) { return ri1.start < ri2.start; });
                                                      ^
/scratch/Shares/layer/workspace/devin_sra/repeat_masker/local/src/INSurVeyor/dc_remapper.cpp:185:54: note:   no known conversion for argument 2 from ‘const remap_info_t’ to ‘remap_info_t&’
In file included from /usr/include/c++/4.8.2/algorithm:62:0,
                 from /scratch/Shares/layer/workspace/devin_sra/repeat_masker/local/src/INSurVeyor/dc_remapper.cpp:6:
/usr/include/c++/4.8.2/bits/stl_algo.h:2266:34: error: no match for call to ‘(get_strict_region_start(std::vector<remap_info_t>&, std::vector<remap_info_t>&)::__lambda14) (const remap_info_t&, remap_info_t&)’
    while (__comp(__pivot, *__last))
                                  ^
/scratch/Shares/layer/workspace/devin_sra/repeat_masker/local/src/INSurVeyor/dc_remapper.cpp:185:16: note: candidates are:
               [](remap_info_t& ri1, remap_info_t& ri2) { return ri1.start < ri2.start; });
                ^
In file included from /usr/include/c++/4.8.2/algorithm:62:0,
                 from /scratch/Shares/layer/workspace/devin_sra/repeat_masker/local/src/INSurVeyor/dc_remapper.cpp:6:
/usr/include/c++/4.8.2/bits/stl_algo.h:2266:34: note: bool (*)(remap_info_t&, remap_info_t&) <conversion>
    while (__comp(__pivot, *__last))
                                  ^
/usr/include/c++/4.8.2/bits/stl_algo.h:2266:34: note:   candidate expects 3 arguments, 3 provided
/scratch/Shares/layer/workspace/devin_sra/repeat_masker/local/src/INSurVeyor/dc_remapper.cpp:185:54: note: get_strict_region_start(std::vector<remap_info_t>&, std::vector<remap_info_t>&)::__lambda14
               [](remap_info_t& ri1, remap_info_t& ri2) { return ri1.start < ri2.start; });
                                                      ^
/scratch/Shares/layer/workspace/devin_sra/repeat_masker/local/src/INSurVeyor/dc_remapper.cpp:185:54: note:   no known conversion for argument 1 from ‘const remap_info_t’ to ‘remap_info_t&’
In file included from /usr/include/c++/4.8.2/algorithm:62:0,
                 from /scratch/Shares/layer/workspace/devin_sra/repeat_masker/local/src/INSurVeyor/dc_remapper.cpp:6:
/usr/include/c++/4.8.2/bits/stl_algo.h: In instantiation of ‘_RandomAccessIterator std::__unguarded_partition(_RandomAccessIterator, _RandomAccessIterator, const _Tp&, _Compare) [with _RandomAccessIterator = __gnu_cxx::__normal_iterator<remap_info_t*, std::vector<remap_info_t> >; _Tp = remap_info_t; _Compare = get_strict_region_end(std::vector<remap_info_t>&, std::vector<remap_info_t>&)::__lambda15]’:
/usr/include/c++/4.8.2/bits/stl_algo.h:2296:78:   required from ‘_RandomAccessIterator std::__unguarded_partition_pivot(_RandomAccessIterator, _RandomAccessIterator, _Compare) [with _RandomAccessIterator = __gnu_cxx::__normal_iterator<remap_info_t*, std::vector<remap_info_t> >; _Compare = get_strict_region_end(std::vector<remap_info_t>&, std::vector<remap_info_t>&)::__lambda15]’
/usr/include/c++/4.8.2/bits/stl_algo.h:2337:62:   required from ‘void std::__introsort_loop(_RandomAccessIterator, _RandomAccessIterator, _Size, _Compare) [with _RandomAccessIterator = __gnu_cxx::__normal_iterator<remap_info_t*, std::vector<remap_info_t> >; _Size = long int; _Compare = get_strict_region_end(std::vector<remap_info_t>&, std::vector<remap_info_t>&)::__lambda15]’
/usr/include/c++/4.8.2/bits/stl_algo.h:5499:44:   required from ‘void std::sort(_RAIter, _RAIter, _Compare) [with _RAIter = __gnu_cxx::__normal_iterator<remap_info_t*, std::vector<remap_info_t> >; _Compare = get_strict_region_end(std::vector<remap_info_t>&, std::vector<remap_info_t>&)::__lambda15]’
/scratch/Shares/layer/workspace/devin_sra/repeat_masker/local/src/INSurVeyor/dc_remapper.cpp:215:85:   required from here
/usr/include/c++/4.8.2/bits/stl_algo.h:2263:35: error: no match for call to ‘(get_strict_region_end(std::vector<remap_info_t>&, std::vector<remap_info_t>&)::__lambda15) (remap_info_t&, const remap_info_t&)’
    while (__comp(*__first, __pivot))
                                   ^
/scratch/Shares/layer/workspace/devin_sra/repeat_masker/local/src/INSurVeyor/dc_remapper.cpp:215:16: note: candidates are:
               [](remap_info_t& ri1, remap_info_t& ri2) { return ri1.end > ri2.end; });
                ^
In file included from /usr/include/c++/4.8.2/algorithm:62:0,
                 from /scratch/Shares/layer/workspace/devin_sra/repeat_masker/local/src/INSurVeyor/dc_remapper.cpp:6:
/usr/include/c++/4.8.2/bits/stl_algo.h:2263:35: note: bool (*)(remap_info_t&, remap_info_t&) <conversion>
    while (__comp(*__first, __pivot))
                                   ^
/usr/include/c++/4.8.2/bits/stl_algo.h:2263:35: note:   candidate expects 3 arguments, 3 provided
/scratch/Shares/layer/workspace/devin_sra/repeat_masker/local/src/INSurVeyor/dc_remapper.cpp:215:54: note: get_strict_region_end(std::vector<remap_info_t>&, std::vector<remap_info_t>&)::__lambda15
               [](remap_info_t& ri1, remap_info_t& ri2) { return ri1.end > ri2.end; });
                                                      ^
/scratch/Shares/layer/workspace/devin_sra/repeat_masker/local/src/INSurVeyor/dc_remapper.cpp:215:54: note:   no known conversion for argument 2 from ‘const remap_info_t’ to ‘remap_info_t&’
In file included from /usr/include/c++/4.8.2/algorithm:62:0,
                 from /scratch/Shares/layer/workspace/devin_sra/repeat_masker/local/src/INSurVeyor/dc_remapper.cpp:6:
/usr/include/c++/4.8.2/bits/stl_algo.h:2266:34: error: no match for call to ‘(get_strict_region_end(std::vector<remap_info_t>&, std::vector<remap_info_t>&)::__lambda15) (const remap_info_t&, remap_info_t&)’
    while (__comp(__pivot, *__last))
                                  ^
/scratch/Shares/layer/workspace/devin_sra/repeat_masker/local/src/INSurVeyor/dc_remapper.cpp:215:16: note: candidates are:
               [](remap_info_t& ri1, remap_info_t& ri2) { return ri1.end > ri2.end; });
                ^
In file included from /usr/include/c++/4.8.2/algorithm:62:0,
                 from /scratch/Shares/layer/workspace/devin_sra/repeat_masker/local/src/INSurVeyor/dc_remapper.cpp:6:
/usr/include/c++/4.8.2/bits/stl_algo.h:2266:34: note: bool (*)(remap_info_t&, remap_info_t&) <conversion>
    while (__comp(__pivot, *__last))
                                  ^
/usr/include/c++/4.8.2/bits/stl_algo.h:2266:34: note:   candidate expects 3 arguments, 3 provided
/scratch/Shares/layer/workspace/devin_sra/repeat_masker/local/src/INSurVeyor/dc_remapper.cpp:215:54: note: get_strict_region_end(std::vector<remap_info_t>&, std::vector<remap_info_t>&)::__lambda15
               [](remap_info_t& ri1, remap_info_t& ri2) { return ri1.end > ri2.end; });
                                                      ^
/scratch/Shares/layer/workspace/devin_sra/repeat_masker/local/src/INSurVeyor/dc_remapper.cpp:215:54: note:   no known conversion for argument 1 from ‘const remap_info_t’ to ‘remap_info_t&’
In file included from /usr/include/c++/4.8.2/algorithm:62:0,
                 from /scratch/Shares/layer/workspace/devin_sra/repeat_masker/local/src/INSurVeyor/dc_remapper.cpp:6:
/usr/include/c++/4.8.2/bits/stl_algo.h: In instantiation of ‘_RandomAccessIterator std::__unguarded_partition(_RandomAccessIterator, _RandomAccessIterator, const _Tp&, _Compare) [with _RandomAccessIterator = __gnu_cxx::__normal_iterator<std::pair<std::basic_string<char>, StripedSmithWaterman::Alignment>*, std::vector<std::pair<std::basic_string<char>, StripedSmithWaterman::Alignment> > >; _Tp = std::pair<std::basic_string<char>, StripedSmithWaterman::Alignment>; _Compare = generate_consensus_sequences(std::string, reads_cluster_t*, reads_cluster_t*, region_t&, bool, bool&, bool&, std::unordered_map<std::basic_string<char>, std::basic_string<char> >&, StripedSmithWaterman::Aligner&, StripedSmithWaterman::Aligner&, std::string&)::__lambda17]’:
/usr/include/c++/4.8.2/bits/stl_algo.h:2296:78:   required from ‘_RandomAccessIterator std::__unguarded_partition_pivot(_RandomAccessIterator, _RandomAccessIterator, _Compare) [with _RandomAccessIterator = __gnu_cxx::__normal_iterator<std::pair<std::basic_string<char>, StripedSmithWaterman::Alignment>*, std::vector<std::pair<std::basic_string<char>, StripedSmithWaterman::Alignment> > >; _Compare = generate_consensus_sequences(std::string, reads_cluster_t*, reads_cluster_t*, region_t&, bool, bool&, bool&, std::unordered_map<std::basic_string<char>, std::basic_string<char> >&, StripedSmithWaterman::Aligner&, StripedSmithWaterman::Aligner&, std::string&)::__lambda17]’
/usr/include/c++/4.8.2/bits/stl_algo.h:2337:62:   required from ‘void std::__introsort_loop(_RandomAccessIterator, _RandomAccessIterator, _Size, _Compare) [with _RandomAccessIterator = __gnu_cxx::__normal_iterator<std::pair<std::basic_string<char>, StripedSmithWaterman::Alignment>*, std::vector<std::pair<std::basic_string<char>, StripedSmithWaterman::Alignment> > >; _Size = long int; _Compare = generate_consensus_sequences(std::string, reads_cluster_t*, reads_cluster_t*, region_t&, bool, bool&, bool&, std::unordered_map<std::basic_string<char>, std::basic_string<char> >&, StripedSmithWaterman::Aligner&, StripedSmithWaterman::Aligner&, std::string&)::__lambda17]’
/usr/include/c++/4.8.2/bits/stl_algo.h:5499:44:   required from ‘void std::sort(_RAIter, _RAIter, _Compare) [with _RAIter = __gnu_cxx::__normal_iterator<std::pair<std::basic_string<char>, StripedSmithWaterman::Alignment>*, std::vector<std::pair<std::basic_string<char>, StripedSmithWaterman::Alignment> > >; _Compare = generate_consensus_sequences(std::string, reads_cluster_t*, reads_cluster_t*, region_t&, bool, bool&, bool&, std::unordered_map<std::basic_string<char>, std::basic_string<char> >&, StripedSmithWaterman::Aligner&, StripedSmithWaterman::Aligner&, std::string&)::__lambda17]’
/scratch/Shares/layer/workspace/devin_sra/repeat_masker/local/src/INSurVeyor/dc_remapper.cpp:591:3:   required from here
/usr/include/c++/4.8.2/bits/stl_algo.h:2263:35: error: no match for call to ‘(generate_consensus_sequences(std::string, reads_cluster_t*, reads_cluster_t*, region_t&, bool, bool&, bool&, std::unordered_map<std::basic_string<char>, std::basic_string<char> >&, StripedSmithWaterman::Aligner&, StripedSmithWaterman::Aligner&, std::string&)::__lambda17) (std::pair<std::basic_string<char>, StripedSmithWaterman::Alignment>&, const std::pair<std::basic_string<char>, StripedSmithWaterman::Alignment>&)’
    while (__comp(*__first, __pivot))
                                   ^
/scratch/Shares/layer/workspace/devin_sra/repeat_masker/local/src/INSurVeyor/dc_remapper.cpp:589:5: note: candidates are:
    [](std::pair<std::string, StripedSmithWaterman::Alignment>& p1, std::pair<std::string, StripedSmithWaterman::Alignment>& p2) {
     ^
In file included from /usr/include/c++/4.8.2/algorithm:62:0,
                 from /scratch/Shares/layer/workspace/devin_sra/repeat_masker/local/src/INSurVeyor/dc_remapper.cpp:6:
/usr/include/c++/4.8.2/bits/stl_algo.h:2263:35: note: bool (*)(std::pair<std::basic_string<char>, StripedSmithWaterman::Alignment>&, std::pair<std::basic_string<char>, StripedSmithWaterman::Alignment>&) <conversion>
    while (__comp(*__first, __pivot))
                                   ^
/usr/include/c++/4.8.2/bits/stl_algo.h:2263:35: note:   candidate expects 3 arguments, 3 provided
/scratch/Shares/layer/workspace/devin_sra/repeat_masker/local/src/INSurVeyor/dc_remapper.cpp:589:127: note: generate_consensus_sequences(std::string, reads_cluster_t*, reads_cluster_t*, region_t&, bool, bool&, bool&, std::unordered_map<std::basic_string<char>, std::basic_string<char> >&, StripedSmithWaterman::Aligner&, StripedSmithWaterman::Aligner&, std::string&)::__lambda17
    [](std::pair<std::string, StripedSmithWaterman::Alignment>& p1, std::pair<std::string, StripedSmithWaterman::Alignment>& p2) {
                                                                                                                               ^
/scratch/Shares/layer/workspace/devin_sra/repeat_masker/local/src/INSurVeyor/dc_remapper.cpp:589:127: note:   no known conversion for argument 2 from ‘const std::pair<std::basic_string<char>, StripedSmithWaterman::Alignment>’ to ‘std::pair<std::basic_string<char>, StripedSmithWaterman::Alignment>&’
In file included from /usr/include/c++/4.8.2/algorithm:62:0,
                 from /scratch/Shares/layer/workspace/devin_sra/repeat_masker/local/src/INSurVeyor/dc_remapper.cpp:6:
/usr/include/c++/4.8.2/bits/stl_algo.h:2266:34: error: no match for call to ‘(generate_consensus_sequences(std::string, reads_cluster_t*, reads_cluster_t*, region_t&, bool, bool&, bool&, std::unordered_map<std::basic_string<char>, std::basic_string<char> >&, StripedSmithWaterman::Aligner&, StripedSmithWaterman::Aligner&, std::string&)::__lambda17) (const std::pair<std::basic_string<char>, StripedSmithWaterman::Alignment>&, std::pair<std::basic_string<char>, StripedSmithWaterman::Alignment>&)’
    while (__comp(__pivot, *__last))
                                  ^
/scratch/Shares/layer/workspace/devin_sra/repeat_masker/local/src/INSurVeyor/dc_remapper.cpp:589:5: note: candidates are:
    [](std::pair<std::string, StripedSmithWaterman::Alignment>& p1, std::pair<std::string, StripedSmithWaterman::Alignment>& p2) {
     ^
In file included from /usr/include/c++/4.8.2/algorithm:62:0,
                 from /scratch/Shares/layer/workspace/devin_sra/repeat_masker/local/src/INSurVeyor/dc_remapper.cpp:6:
/usr/include/c++/4.8.2/bits/stl_algo.h:2266:34: note: bool (*)(std::pair<std::basic_string<char>, StripedSmithWaterman::Alignment>&, std::pair<std::basic_string<char>, StripedSmithWaterman::Alignment>&) <conversion>
    while (__comp(__pivot, *__last))
                                  ^
/usr/include/c++/4.8.2/bits/stl_algo.h:2266:34: note:   candidate expects 3 arguments, 3 provided
/scratch/Shares/layer/workspace/devin_sra/repeat_masker/local/src/INSurVeyor/dc_remapper.cpp:589:127: note: generate_consensus_sequences(std::string, reads_cluster_t*, reads_cluster_t*, region_t&, bool, bool&, bool&, std::unordered_map<std::basic_string<char>, std::basic_string<char> >&, StripedSmithWaterman::Aligner&, StripedSmithWaterman::Aligner&, std::string&)::__lambda17
    [](std::pair<std::string, StripedSmithWaterman::Alignment>& p1, std::pair<std::string, StripedSmithWaterman::Alignment>& p2) {
                                                                                                                               ^
/scratch/Shares/layer/workspace/devin_sra/repeat_masker/local/src/INSurVeyor/dc_remapper.cpp:589:127: note:   no known conversion for argument 1 from ‘const std::pair<std::basic_string<char>, StripedSmithWaterman::Alignment>’ to ‘std::pair<std::basic_string<char>, StripedSmithWaterman::Alignment>&’
make[2]: *** [CMakeFiles/dc_remapper.dir/dc_remapper.cpp.o] Error 1
make[1]: *** [CMakeFiles/dc_remapper.dir/all] Error 2
make: *** [all] Error 2`

**Comment by Mesh89** [comment]
Hi,

It seems your GCC version is too old, and does not support some C++ features.
Can you try a newer version? 4.9.3 works for me.

In case you cannot, I recommend either building a docker image with the provided Dockerfile, or using the provided singularity image.

**Comment by mrburke00** [comment]
Awesome. Upgrading the GCC did fix that error, but I am running into a ton of clashes with my conda environment. Im switching to trying out the singularity image instead.  I have a few issues with that. I will make a separate post about it.  Appreciate the help.
