### ISSUE TITLE
use csi

### ISSUE THREAD

**Issue by GuyBenzvi** [kensung-lab/INSurVeyor#20]
hey,
i need assistance with a recurring problem, im working on 1A chromosom in wheat genome with the use of  --use-csi dependency, for some of my accessions i get the following error and in some i dont, and when im tring to test the whole genome of an accession that gave me result for chromosm 1A im getting that same error  

 
[E::hts_idx_check_range] Region 574767067..574767106 cannot be stored in a bai index. Try using a csi index
[E::sam_index] Read 'A00977:180:HLMWFDSXY:3:2535:19868:21746' with ref_name='lcl|chr1A', ref_length=585266722, flags=1145, pos=574767068 cannot be indexed
terminate called after throwing an instance of 'std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >'
Aborted (core dumped)
DC remapped in 723 [s]
Executing: INSurVeyor/add_filtering_info chr1A.sortname.mc.s.bam . chr1A.fa
[E::hts_open_format] Failed to open file "./assembled_ins.vcf.gz" : No such file or directory
Segmentation fault (core dumped)
Filtering info added in 0 [s]
Executing: INSurVeyor/filter . chr1A.fa 0.25
[E::hts_open_format] Failed to open file "./transurveyor_ins.annotated.vcf.gz" : No such file or directory
terminate called after throwing an instance of 'std::runtime_error'
  what():  Unable to open file ./transurveyor_ins.annotated.vcf.gz.
Aborted (core dumped)

**Comment by Mesh89** [comment]
Hi,
Can you try the latest commit?

**Comment by GuyBenzvi** [comment]
Hi,
i tried the last commit, 
the use csi opption is shown in my help segment
and for some accessions the pipeline does works for me

Thanks in advance,

**Comment by Mesh89** [comment]
Sorry, I am not sure I understand correctly.

Have you tried the latest commit? Can you confirm by running git pull?

**Comment by GuyBenzvi** [comment]
I just did the last commit and it fixed problem for some of the samples,
 
  but i got new errors for some of them: 
 [E::hts_idx_check_range] Region 539501541..539502069 cannot be stored in a tbi index. Try using a csi index

**Comment by Mesh89** [comment]
It seems we need to use csi indexes for vcf files as well. 
The only time INSurVeyor indexes a vcf file is after the final result has been produced, so your runs should in fact be successful (just that the out.pass.vcf.gz was not indexed). Let me know if this is the case.
In the meantime, I pushed a commit that uses csi files for indexing vcf files as well.
