### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by Meetmet21** [kensung-lab/INSurVeyor#21]
Hello,

I have a curious error when I'm using two different BAM files. Both are generated by the same pipeline. First the pipeline starts by sorting by name via samtools sort -n to add fixmate tags latter on again with samtools. Then, I sort back by coordinates the given bam and I index it. The problem is that I have one BAM with which insurveyor works and another one does not. I use insurveyor image 1.1.2. 

The error that I get is: 

terminate called after throwing an instance of 'std::system_error'
  what():  Invalid argument
Aborted (core dumped)
terminate called after throwing an instance of 'std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >'
Aborted (core dumped)
terminate called after throwing an instance of 'std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >'
Aborted (core dumped)
[E::hts_open_format] Failed to open file "test/assembled_ins.vcf.gz" : No such file or directory
Segmentation fault (core dumped)
[E::hts_open_format] Failed to open file "test/transurveyor_ins.annotated.vcf.gz" : No such file or directory
terminate called after throwing an instance of 'std::runtime_error'
  what():  Unable to open file test/transurveyor_ins.annotated.vcf.gz.
Aborted (core dumped)

Here is the command i used: 
singularity  run -B /path/to/bamdir/ -B /path/to/regenomedir/  -B $PWD/test/  insurveyor.sif--threads 12 /path/to/bamfile test /path/to/refgenomefile

Do you have any idea ?

Cheers.

PS:
1 read from the bam with which INSurVeyor don't work:
(masked)    81      1       9996    0       77S73M  2       182140523       0       CCCCCCCCCCCCACCCTCTCTCAATCACAACACGTCATTCGATCTCTTGGCGTTACTGTAGTTCTTACGTGTGCTCTTCCGATATCCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTA       ,F,F,:FFFF,F,,,F:,,,,FF,,F,,:F,,,,,,F,,,:F,,:,FF,,,FF:F,F,,:,,F,,,,FFF:,,F,:FF,,,:F,:,,F,FFF,FF:FFFFF:FF:FFFF::FFFFFF,FFFFF:FFFF,FFFFFFFFFFFFFFF:FFFFF       PG:Z:MarkDuplicates AS:i:68  XS:i:65 MD:Z:0N0N0N0N0N2A65     NM:i:6  RG:Z:NA_12878   MQ:i:0  MC:Z:62M88S     ms:i:4264
1 from the one that works:
(masked)     65      1       9999    0       40S66M42S       5       18606432        0       GAGTTGCCTAGAACAGCTCTTCCTTTATTTTCTTTTTCTGGATAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACAGAGATAACTATTGATACAACACCTTCATGACCCTAAGGTAC @??DFEFDADFHHIIFGHIIIEIIIIIIIIIICHIGICFGG*?BDDGEHIIIHGB@BGECHEBCHGIIGCGEFEE?B?BDEBCABC?ABBDDDB?ABDDD??AAAA>ADC9CCCCDDCDDC>CCDCC@?BDACD@>CC>A?C9>?@A: SA:Z:5,18606943,-,99S49M,0,0;5,18606892,-,44M104S,0,0;       PG:Z:MarkDuplicates     AS:i:66 XS:i:65 MD:Z:0N0N64     NM:i:2  RG:Z:DM_20_9999 MQ:i:60 MC:Z:148M       ms:i:3678

**Comment by Mesh89** [comment]
Hi,

I am puzzled by the std::system_error. The subsequent errors are just a consequence of that error.
A few things I would need:

1) Can you check that the BAM works with other callers, for instance Manta?
2) Can you provide me with the full output, not just the error message?
3) Can you provide me with the core dump?

**Comment by Meetmet21** [comment]
Hello,

1) Yes, the BAM seems to work with Manta.
2) 
<< output from stdout >>
Categorizing 1
Categorizing 2
Categorizing 3
Categorizing 5
Categorizing 4
Categorizing 6
Categorizing 7
Categorizing 8
Categorizing 9
Categorizing 10
Categorizing 11
Categorizing 12
Categorizing 14
Categorizing 13
Categorizing 16
Categorizing 15
Categorizing 17
Categorizing 19
Categorizing 18
Categorizing 20
Categorizing 21
Categorizing 22
Categorizing X
Categorizing Y
Categorizing MT
Categorizing 1_gl000191_random
Categorizing 1_gl000192_random
Categorizing 4_gl000193_random
Categorizing 4_gl000194_random
Categorizing 7_gl000195_random
Categorizing 8_gl000196_random
Categorizing 8_gl000197_random
Categorizing 9_gl000198_random
Categorizing 9_gl000199_random
Categorizing 9_gl000200_random
Categorizing 9_gl000201_random
Categorizing 11_gl000202_random
Categorizing 17_gl000203_random
Categorizing 17_gl000204_random
Categorizing 17_gl000205_random
Categorizing 17_gl000206_random
Categorizing 18_gl000207_random
Categorizing 19_gl000208_random
Categorizing 19_gl000209_random
Categorizing 21_gl000210_random
Categorizing Un_gl000211
Categorizing Un_gl000212
Categorizing Un_gl000213
Categorizing Un_gl000214
Categorizing Un_gl000215
Categorizing Un_gl000216
Categorizing Un_gl000217
Categorizing Un_gl000218
Categorizing Un_gl000219
Categorizing Un_gl000220
Categorizing Un_gl000221
Categorizing Un_gl000222
Categorizing Un_gl000223
Categorizing Un_gl000224
Categorizing Un_gl000225
Categorizing Un_gl000226
Categorizing Un_gl000227
Categorizing Un_gl000228
Categorizing Un_gl000229
Categorizing Un_gl000230
Categorizing Un_gl000231
Categorizing Un_gl000232
Categorizing Un_gl000233
Categorizing Un_gl000234
Categorizing Un_gl000235
Categorizing Un_gl000236
Categorizing Un_gl000237
Categorizing Un_gl000238
Categorizing Un_gl000239
Categorizing Un_gl000240
Categorizing Un_gl000241
Categorizing Un_gl000242
Categorizing Un_gl000243
Categorizing Un_gl000244
Categorizing Un_gl000245
Categorizing Un_gl000246
Categorizing Un_gl000247
Categorizing Un_gl000248
Categorizing Un_gl000249
Building consensuses for 1
Building consensuses for 9
Building consensuses for 8
Building consensuses for 5
Building consensuses for 6
Building consensuses for 11
Building consensuses for 3
Building consensuses for 4
Building consensuses for 2
Building consensuses for 7
Building consensuses for 12
Building consensuses for 10
Building consensuses for 14
Building consensuses for 13
Building consensuses for 15
Building consensuses for 16
Building consensuses for 17
Building consensuses for 22
Building consensuses for 21
Building consensuses for Y
Building consensuses for X
Building consensuses for 18
Building consensuses for 20
Building consensuses for MT
Building consensuses for 1_gl000191_random
Building consensuses for 4_gl000193_random
Building consensuses for 1_gl000192_random
Building consensuses for 4_gl000194_random
Building consensuses for 7_gl000195_random
Building consensuses for 8_gl000197_random
Building consensuses for 8_gl000196_random
Building consensuses for 11_gl000202_random
Building consensuses for 9_gl000201_random
Building consensuses for 9_gl000200_random
Building consensuses for 9_gl000199_random
Building consensuses for 9_gl000198_random
Building consensuses for 17_gl000203_random
Building consensuses for 17_gl000205_random
Building consensuses for 17_gl000204_random
Building consensuses for 18_gl000207_random
Building consensuses for 17_gl000206_random
Building consensuses for 19_gl000209_random
Building consensuses for 21_gl000210_random
Building consensuses for 19_gl000208_random
Building consensuses for Un_gl000211
Building consensuses for Un_gl000213
Building consensuses for Un_gl000214
Building consensuses for Un_gl000212
Building consensuses for Un_gl000215
Building consensuses for Un_gl000216
Building consensuses for Un_gl000217
Building consensuses for Un_gl000218
Building consensuses for Un_gl000219
Building consensuses for Un_gl000220
Building consensuses for Un_gl000222
Building consensuses for Un_gl000221
Building consensuses for Un_gl000224
Building consensuses for Un_gl000223
Building consensuses for Un_gl000225
Building consensuses for Un_gl000226
Building consensuses for Un_gl000227
Building consensuses for Un_gl000230
Building consensuses for Un_gl000229
Building consensuses for Un_gl000231
Building consensuses for Un_gl000228
Building consensuses for Un_gl000232
Building consensuses for Un_gl000233
Building consensuses for Un_gl000236
Building consensuses for Un_gl000239
Building consensuses for Un_gl000237
Building consensuses for Un_gl000241
Building consensuses for Un_gl000235
Building consensuses for Un_gl000240
Building consensuses for Un_gl000234
Building consensuses for Un_gl000238
Building consensuses for Un_gl000242
Building consensuses for Un_gl000243
Building consensuses for Un_gl000244
Building consensuses for Un_gl000245
Building consensuses for Un_gl000246
Building consensuses for Un_gl000247
Building consensuses for Un_gl000248
Building consensuses for Un_gl000249
Calling insertions for 1
Calling insertions for 2
Calling insertions for 5
Calling insertions for 6
Calling insertions for 3
Calling insertions for 4
Calling insertions for 8
Calling insertions for 7
Calling insertions for 9
Calling insertions for 10
Calling insertions for 11
Calling insertions for 12
Calling insertions for 13
Calling insertions for 14
Calling insertions for 15
Calling insertions for 16
Calling insertions for 17
Calling insertions for 18
Calling insertions for 19
Calling insertions for 20
Calling insertions for 21
Calling insertions for 22
Calling insertions for X
Calling insertions for Y
Calling insertions for MT
Calling insertions for 1_gl000191_random
Calling insertions for 1_gl000192_random
Calling insertions for 4_gl000193_random
Calling insertions for 4_gl000194_random
Calling insertions for 7_gl000195_random
Calling insertions for 8_gl000196_random
Calling insertions for 8_gl000197_random
Calling insertions for 9_gl000198_random
Calling insertions for 9_gl000199_random
Calling insertions for 9_gl000200_random
Calling insertions for 9_gl000201_random
Calling insertions for 11_gl000202_random
Calling insertions for 17_gl000203_random
Calling insertions for 17_gl000204_random
Calling insertions for 17_gl000205_random
Calling insertions for 17_gl000206_random
Calling insertions for 18_gl000207_random
Calling insertions for 19_gl000208_random
Calling insertions for 19_gl000209_random
Calling insertions for 21_gl000210_random
Calling insertions for Un_gl000211
Calling insertions for Un_gl000212
Calling insertions for Un_gl000213
Calling insertions for Un_gl000214
Calling insertions for Un_gl000215
Calling insertions for Un_gl000216
Calling insertions for Un_gl000217
Calling insertions for Un_gl000218
Calling insertions for Un_gl000219
Calling insertions for Un_gl000220
Calling insertions for Un_gl000221
Calling insertions for Un_gl000222
Calling insertions for Un_gl000223
Calling insertions for Un_gl000224
Calling insertions for Un_gl000225
Calling insertions for Un_gl000226
Calling insertions for Un_gl000227
Calling insertions for Un_gl000228
Calling insertions for Un_gl000229
Calling insertions for Un_gl000230
Calling insertions for Un_gl000231
Calling insertions for Un_gl000232
Calling insertions for Un_gl000233
Calling insertions for Un_gl000234
Calling insertions for Un_gl000235
Calling insertions for Un_gl000236
Calling insertions for Un_gl000237
Calling insertions for Un_gl000238
Calling insertions for Un_gl000239
Calling insertions for Un_gl000240
Calling insertions for Un_gl000241
Calling insertions for Un_gl000242
Calling insertions for Un_gl000243
Calling insertions for Un_gl000244
Calling insertions for Un_gl000245
Calling insertions for Un_gl000246
Calling insertions for Un_gl000247
Calling insertions for Un_gl000248
Calling insertions for Un_gl000249
Remapping DC for 9
Remapping DC for 13
Remapping DC for 3
Remapping DC for 14
Remapping DC for 15
Remapping DC for 16
Remapping DC for 18
Remapping DC for 21
Remapping DC for 22
Remapping DC for 4_gl000193_random
Remapping DC for 9_gl000199_random
Remapping DC for 11_gl000202_random
Remapping DC for 17_gl000204_random
Remapping DC for 18_gl000207_random
Remapping DC for 19_gl000209_random
Remapping DC for 19_gl000208_random
Remapping DC for Un_gl000212
Remapping DC for Un_gl000214
Remapping DC for Un_gl000217
Remapping DC for Un_gl000216
Remapping DC for Un_gl000218
Remapping DC for Un_gl000219
Remapping DC for Un_gl000222
Remapping DC for Un_gl000225
Remapping DC for Un_gl000230
Remapping DC for Un_gl000229
Remapping DC for Un_gl000231
Remapping DC for Un_gl000233
Remapping DC for Un_gl000232
Remapping DC for Un_gl000235
Remapping DC for Un_gl000241

<< output from stderr >>
terminate called after throwing an instance of 'std::system_error'
  what():  Invalid argument
Aborted (core dumped)
terminate called after throwing an instance of 'std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >'
Aborted (core dumped)
terminate called after throwing an instance of 'std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >'
Aborted (core dumped)
[E::hts_open_format] Failed to open file "test/assembled_ins.vcf.gz" : No such file or directory
Segmentation fault (core dumped)
3)
$ file core.13469 
core.13469: ELF 64-bit LSB core file x86-64, version 1 (SYSV), SVR4-style, from '/home/reads_categorizer /path/to/pipeline/dir', real uid: 31256, effective uid: 31256, real gid: 63406, effective gid: 63406, execfn: '/home/reads_categorizer', platform: 'x86_64'
$ file core.13513
core.13513: ELF 64-bit LSB core file x86-64, version 1 (SYSV), SVR4-style, from '/home/clip_consensus_builder test /path/to/ref/genome', real uid: 31256, effective uid: 31256, real gid: 63406, effective gid: 63406, execfn: '/home/clip_consensus_builder', platform: 'x86_64
$ file core.13584
core.13584: ELF 64-bit LSB core file x86-64, version 1 (SYSV), SVR4-style, from '/home/dc_remapper test /path/to/ref/genome', real uid: 31256, effective uid: 31256, real gid: 63406, effective gid: 63406, execfn: '/home/dc_remapper', platform: 'x86_64'
etc...

Here is what I could get. Thanky you very much for your help.
Cheers.

**Comment by Meetmet21** [comment]
Hello,

So i resolved the problem by changing samtools version. I was using the version 1.19.* and I changed it to 1.12.* which works very well with INSurVeyor. 

Cheers.
