### ISSUE TITLE
Invalid Contig Error

### ISSUE THREAD

**Issue by caroolcardooso-uwa** [kensung-lab/INSurVeyor#22]
Hey there! 
I'm trying to run INSurVeyor iusing WGS .bam files using conda, but I'm facing the following error:

Traceback (most recent call last):
  File "/scratch/conda_envs/insurveyor-env/bin/insurveyor.py", line 104, in <module>
    for read in bam_file.fetch(contig=chr, start=pos, end=pos+10000):
  File "pysam/libcalignmentfile.pyx", line 1091, in pysam.libcalignmentfile.AlignmentFile.fetch
  File "pysam/libchtslib.pyx", line 685, in pysam.libchtslib.HTSFile.parse_region
ValueError: invalid contig `chr16_KZ559113v1_fix`

Any idea of what might be going on?

Thank you!

**Comment by Mesh89** [comment]
Hi,

I suspect that your reference fasta file contains chr16_KZ559113v1_fix while your bam does not, i.e., it was mapped against a reference that does not contain it.

Can you check if this is the case? You can check with

samtools view -H bam_file | grep chr16_KZ559113v1_fix

If it does not contain it, that is the issue.

**Comment by caroolcardooso-uwa** [comment]
Hey!

Yes, that was exactly the case! Thanks a lot!
Do you know if there's a way to skip those cases? 

Thanks!

**Comment by Mesh89** [comment]
Can you use the reference that was used for mapping? If there are some differences in the contigs themselves, it may lead to results being very unreliable.
