### ISSUE TITLE
[E::hts_open_format] Failed to open file

### ISSUE THREAD

**Issue by Myno-Jeong** [kensung-lab/INSurVeyor#23]
Hi, Thank you for making INSurVeyor program.
Unfortunately, when I ran this program, the following problem occurred.
-------------------
Remapping DC for chr4_GL000008v2_random
DC remapped in 6 [s]
Executing: /home/users/mhjeong/miniconda3/envs/insurveyor-env/bin/add_filtering_info
[E::hts_open_format] Failed to open file "INSurVeyor/wrk_space/assembled_ins.vcf.gz" : No such file or directory"
-----------------------------
I installed INSurVeyor using miniconda (version: 23.3.1) and I checked the version of installed htslib (version: 1.16).
I think you updated INsurVeyor and htslib version (1.16 -> 1.19.1)
Also, I checked small_ins.vcf.gz is created.

About setting of INSurVeyor using Docker, I think you have to update dockerfile for installing INSurVeyor without error messages.
In dockerfile, htslib used version 1.16. but, you have provided version 1.19.1.

Would you let me know how I solve this problem?

Thank you,
best regards,

**Comment by kp2657** [comment]
Hi, I was wondering how you solved this as I am encountering the same issue. Thanks!

**Comment by Mesh89** [comment]
Hi,

Is the dataset you are using publicly available? Would it be possible for me to try it?

**Comment by kp2657** [comment]
Hi, the data isn't publicly available, but I can provide access over email.

**Comment by Mesh89** [comment]
That would be helpful. You can add gmail.com to my username.

**Comment by kp2657** [comment]
Great, sent!

**Comment by Mesh89** [comment]
Hi,

the problem seems to be that the NM tag is not present. You can easily add it with samtools:

http://www.htslib.org/doc/samtools-calmd.html

**Comment by kp2657** [comment]
Ah thank you so much, works now!
