### ISSUE TITLE
Warning: mate not found and does not have an MQ tag

### ISSUE THREAD

**Issue by shilpasy** [kensung-lab/INSurVeyor#24]

**Comment by heidihyang** [comment]
Hi! Were you able to find a solution to the mate not found warnings? Or did you disregard them? Thanks!

**Comment by Mesh89** [comment]
Hi,

Sorry for the delay. Can you confirm that both MC and MQ are properly set for all reads?
The warnings contain the name of some reads. Could print a few of them and post them here?
