### ISSUE TITLE
Please provide benchmark VCFs used in paper

### ISSUE THREAD

**Issue by jdidion** [kensung-lab/INSurVeyor#27]
In your [paper](https://www.nature.com/articles/s41467-023-38870-2#data-availability) you say that you removed tandem duplications from the benchmark sets. Could you provide the VCFs with tandem duplications removed to facilitate benchmarking your tool and reproducing your results? Thank you!

**Comment by Mesh89** [comment]
Hi, please find them here:

https://zenodo.org/records/13766485

Let me know if you need anything else or if you have troubles with the files provided.

**Comment by jdidion** [comment]
Thank you!

**Comment by jdidion** [comment]
@Mesh89 - to  be more specific, do you have the GIAB v0.6 benchmark set with dups removed? Thanks

**Comment by Mesh89** [comment]
[HG002_SVs_Tier1_v0.6.INS.PASS.noDUP.vcf.gz](https://github.com/user-attachments/files/17024941/HG002_SVs_Tier1_v0.6.INS.PASS.noDUP.vcf.gz)

Here it is.

**Comment by jdidion** [comment]
Thank you!On Sep 17, 2024, at 1:12 AM, Mesh89 ***@***.***> wrote:﻿
HG002_SVs_Tier1_v0.6.INS.PASS.noDUP.vcf.gz
Here it is.
