### ISSUE TITLE
[W::bam_hdr_read] EOF marker is absent. The input is probably truncated

### ISSUE THREAD

**Issue by Kanglu123** [kensung-lab/INSurVeyor#28]
Hi,
 I used a cram file generated by samtools sort and fixmate, to run clip_consensus_builder, the command look like this:
"~/miniconda3/envs/insurveyor-env/bin/clip_consensus_builder HGDP00092.alt_bwamem_GRCh38DH.20181023.Balochi.cram GRCh38_full_analysis_set_plus_decoy_hla.fa"
When processed chr17-chr22, I encountered the error "[W::bam_hdr_read] EOF marker is absent. The input is probably truncated", but when run "samtools quickcheck -vvv HGDP00092.alt_bwamem_GRCh38DH.20181023.Balochi.cram", the cram file passed check.
Would you mind give some suggestions for this issue? Many thanks.
samtools version: 1.21

**Comment by Mesh89** [comment]
INSurVeyor must be run using the provided insurveyor.py, i.e.

insurveyor.py --threads N_THREADS BAM_FILE WORKDIR REFERENCE_FASTA
