### ISSUE TITLE
Singularity issues

### ISSUE THREAD

**Issue by mrburke00** [kensung-lab/INSurVeyor#3]
Could you clarify some aspects of using the singularity file? 
Does the working directory need to include the reference and alignment files? 
I first tried running it with this command from within the INSurVeyor repo.
```
singularity run insurveyor.sif 
     --threads 32 
     repeat_masker/data/horse/SRR1046147.sorted.bam 
     repeat_masker/data/horse 
     repeat_masker/data/horse/Equus_caballus.EquCab3.0.dna.toplevel.fa
```
Which resulted in 
```
File "surveyor.py", line 39, in <module>
    config_file = open(cmd_args.workdir + "/config.txt", "w")
    IOError: [Errno 2] No such file or directory: 'repeat_masker/data/horse/config.txt'
```
I get this type of error even when I pass in the full paths of each item. 
I then tried running the following command from the root directory
```
singularity run local/src/INSurVeyor/insurveyor.sif 
     --threads 32 
     repeat_masker/data/horse/SRR1046147.sorted.bam 
     repeat_masker/data/horse 
     repeat_masker/data/horse/Equus_caballus.EquCab3.0.dna.toplevel.fa
```
and I get
```
/usr/bin/python: can't open file 'surveyor.py': [Errno 2] No such file or directory
```
This type of stuff is definitely not my strong suit, but I cant tell if these errors are coming from some issue in my directory structuring around the INSurVeyor repo.

**Comment by mrburke00** [comment]
Actually i might have found the issue with the `config.txt` file.  I initially had the working directory set as a different directory.  That directory has the `config.txt` file.  But when I change that working directory argument it doesn't recreate the `config.txt` file.

**Comment by mrburke00** [comment]
Oops didnt mean to close that issue just yet

**Comment by msubirana** [comment]
hi! I'm having the same problem, any solution instead of moving the files?

**Comment by Mesh89** [comment]
By default, Singularity binds your home and a few system directories. If you need to access files that are not within those directories, you may have to bind the directory you need.

https://docs.sylabs.io/guides/3.0/user-guide/bind_paths_and_mounts.html

**Comment by msubirana** [comment]
hi I tried like this:

threads=1
sample=NET101
bam=/main/marc/insulinomas/data/WES/BAM/all_bams/NET101_TI.bam
workdir_tumor=/main/marc/insulinomas/insurveyor/insurveyor/${sample}/tumor
reference=/main/ref/GCA_000001405.15_GRCh38_no_alt_analysis_set.fa

singularity run --bind
/gpfs42/robbyfs/scratch/lab_lpasquali/msubirana/:/main $SINGULARITY_IMAGES
/insurveyor.sif \
--threads $threads $bam $workdir_tumor $reference

and I got the same error:

Traceback (most recent call last):
  File "/home/surveyor.py", line 39, in <module>
    config_file = open(cmd_args.workdir + "/config.txt", "w")
IOError: [Errno 2] No such file or directory:
'/main/marc/insulinomas/insurveyor/insurveyor/NET101/tumor/config.txt'

**Comment by mrburke00** [comment]
Yeah I still haven't figure out a way besides moving the files to within the insurveyor directory.  I then have to load singularity within the output directory.  I haven't been able to run it in parallel as a result.  Ill write my file structure below so you can hopefully get it running. 
```
> insurveyor
     > output
                config.txt
     > data
                all my bams are here 
```
I then navigate to `output` directory and for my system run `module load singularity`.
Then I run 
```
singularity run insurveyor.sif  --threads $threads data/$bam output data/$ref
```
I've tried to debug this in many different ways but the above is the only way I have gotten to work so far.

**Comment by Mesh89** [comment]
It seems to me that your desired workdir is 

/gpfs42/robbyfs/scratch/lab_lpasquali/msubirana/marc/insulinomas/insurveyor/insurveyor/${sample}/tumor

Is that correct? Does it exist at the moment of execution? The workdir must exist for INSurVeyor to work.
The error you see is because it failed to write a file to the workdir, usually because it does not exist or it does not have permissions to do that.
