### ISSUE TITLE
Config file is not recreated when changing output directory

### ISSUE THREAD

**Issue by mrburke00** [kensung-lab/INSurVeyor#5]
Im trying to create a pipeline to look at hundreds of samples called using the tool.  When you try and create a unique output directory the config file is never recreated. 

First command (runs to completion):
> singularity run insurveyor.sif --threads 32 data/SRR1046147.fixed.bam output/SRR1046147 data/Equus_caballus.EquCab3.0.dna.toplevel.fa

Second command (fails):
> singularity run insurveyor.sif --threads 32 data/SRR5567.fixed.bam output/SRR5567 data/Equus_caballus.EquCab3.0.dna.toplevel.fa

Error:
>Traceback` (most recent call last):
  File "/home/surveyor.py", line 39, in <module>
    config_file = open(cmd_args.workdir + "/config.txt", "w")
IOError: [Errno 2] No such file or directory: 'output/SRR5567/config.txt'

This problem persists even if I try and copy the original config file to a new directory.

**Comment by Mesh89** [comment]
For some reason, INSurVeyor failed to write to output/SRR5567. 
Can you check that output/SRR5567 exists and is writable?
Furthermore, can you try and use absolute paths?

**Comment by mrburke00** [comment]
It appears that I had an issue with where I was loading the singularity module.  Loading it while inside the existing output directory seemed to have fixed the issue.  The program still does not recreate the config file for some reason. Not a huge deal though I can just copy the preexisting config file to each output directory in the pipeline.
