### ISSUE TITLE
INSurVeyor WES

### ISSUE THREAD

**Issue by msubirana** [kensung-lab/INSurVeyor#7]
Hi,

Is it possible to use INSurVeyor in WES data?

**Comment by Mesh89** [comment]
I never tried, but in theory it should work. The only issue I see is that the algorithm samples random locations in the genome to determine things like insert size distribution, coverage distribution, etc. For WES, most of those locations will be empty.

You could create a BED file with the locations of the exons and pass it to the software with the --sampling-regions option. Let me know how if it works.

**Comment by msubirana** [comment]
yes is working thanks!
